version: '3'
services:
  mysql:
    image: mysql:8.0.33
    container_name: mysql-db
    environment:
      MYSQL_DATABASE: 'student_tracker'
      MYSQL_USER: 'marie'
      MYSQL_PASSWORD: 'curie'
      MYSQL_ROOT_PASSWORD: 'radium'
    ports:
      - "3306:3306"
    volumes:
      - mysql_volume:/var/lib/mysql
volumes:
  mysql_volume: