spring:
  main:
    banner-mode: off
  security:
    user:
      name: fredrik
      password: potatis
  datasource:
    url: jdbc:mysql://localhost:3306/student_tracker
    username: marie
    password: curie
  jpa:
    show-sql: true
    open-in-view: true
    hibernate:
      ddl-auto: update


management:
  info:
    env:
      enabled: true
    java:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,mappings

player:
  name: Patrick Polly

info:
  app:
    name: My Super Cool App
    description: A crazy and fun app, Yoohoo!
    version: 1.0.0

logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace