spring:
  security:
    user:
      name: fredrik
      password: potatis
  datasource:
    #url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/student_tracker
    url: jdbc:mysql://localhost:3306/student_tracker
    username: marie
    password: curie


management:
  info:
    env:
      enabled: true
    java:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,mappings

player:
  name: Patrick Polly

info:
  app:
    name: My Super Cool App
    description: A crazy and fun app, Yoohoo!
    version: 1.0.0

#Exempel kommentar